version: '3.4'

services:
  # 1. Start database
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./backup/:/var/lib/mysql:ro
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8090:80
    restart: always
  keycloak:
    build: ./keycloak
    ports:
      - "8443:8443"
    environment:
      KC_HOSTNAME: ${KC_HOSTNAME}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
      # change these values to point to a running mysql instance
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${MYSQL_USER}
      KC_DB_PASSWORD: ${MYSQL_PASSWORD}
    command:
      - start
      - --optimized
      - --import-realm
    depends_on:
      - mysql
    volumes:
      - ./keycloak/demo-realm.json:/opt/keycloak/data/import/realm.json
    restart: unless-stopped

  # # 2. Add env variable from keycloak to server .env, then start server and another service
  # wallet-server:
  #   build: ./api
  #   ports:
  #     - "5555:5555"
  #   restart: unless-stopped
  # auction-client:
  #   build: ./auction-client
  #   ports:
  #       - "3001:80"
  #   restart: unless-stopped
  # wallet-client:
  #   build: ./wallet-management
  #   ports:
  #       - "3000:80"
  #   restart: unless-stopped
  # dms:
  #   build: ./dms
  #   ports:
  #       - "3002:80"
  #   restart: unless-stopped
