version: '3.4'
name: ecosystem-service
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - ${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}
    volumes:
      - ./api/backup-mongo:/data/db
    networks:
      - node-webapp-network
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/
    networks:
      - node-webapp-network
  wallet-server:
    depends_on:
      - mongodb
    build: ./api
    ports:
      - "5555:5555"
    networks:
      - node-webapp-network
    restart: always
  auction-client:
    build: ./auction-client
    ports:
        - "3001:80"
    restart: always
  wallet-client:
    build: ./wallet-management
    ports:
        - "3000:80"
    restart: always
  dms:
    build: ./dms
    ports:
        - "3002:80"
    restart: always
networks:
  node-webapp-network:
    driver: bridge
