version: '3.4'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT}
    ports:
      - 8090:80
    restart: unless-stopped
  mysql-backup:
    image: databack/mysql-backup
    container_name: mysql-backup
    depends_on:
      - mysql
    environment:
      DB_SERVER: mysql
      DB_PORT: ${MYSQL_PORT}
      DB_NAMES: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_ROOT_USER}
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      DB_DUMP_TARGET: "/db ${AWS_S3_DESTINATION}"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      DB_DUMP_FREQ: 600
      DB_DUMP_BEGIN: '+5'
      DB_DUMP_SAFECHARS: no-colons
      DB_DUMP_DEBUG: 'true'
      #DB_RESTORE_TARGET: /db/db_backup_****-**-**T**-**-**Z.tgz
    volumes:
      - ./keycloak/backup/:/db
    restart: unless-stopped
  keycloak:
    build: ./keycloak
    ports:
      - "${KC_HOSTNAME_PORT}:8443"
    environment:
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_PORT: ${KC_HOSTNAME_PORT}
      KC_HOSTNAME_URL: ${KC_HOSTNAME_URL}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
      # change these values to point to a running mysql instance
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${MYSQL_USER}
      KC_DB_PASSWORD: ${MYSQL_PASSWORD}
    command:
      - start
      - --optimized
      # - --import-realm
    depends_on:
      - mysql
    restart: unless-stopped
