version: '3.8'

services:
  db:
    container_name: mongo
    env_file: ./.env
    build:
      context: ./mongo
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - ${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}
    networks:
      - proxynet
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@db:${MONGODB_DOCKER_PORT}/
    networks:
      - proxynet
  wallet-server:
    depends_on:
      - db
    build: ./
    ports:
      - "5555:5555"
    restart: always
    networks:
      - proxynet
  auction-client:
    build: ../auction-client
    ports:
        - "3001:80"
    restart: always
    networks:
      - proxynet
  wallet-client:
    build: ../wallet-management
    ports:
        - "3000:80"
    restart: always
    networks:
      - proxynet
  dms:
    build: ../dms
    ports:
        - "3002:80"
    restart: always
    networks:
      - proxynet
networks:
  proxynet:
    external:
      name: custom_network
